services:
  frontend:
    build:
      context: .
      target: build-stage
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    command: npm run dev
    networks:
      - task-manager-network

networks:
  task-manager-network:
    name: task-manager-network
    external: true
